/*! Blob.js
 * A Blob implementation.
 * 2013-01-23
 *
 * By Eli Grey, http://eligrey.com
 * By Devin Samarin, https://github.com/eboyjr
 * License: X11/MIT
 *   See LICENSE.md
 */
/*! @source http://purl.eligrey.com/github/Blob.js/blob/master/Blob.js */
if(typeof Blob!=="function"){var Blob=(function(a){var b=a.BlobBuilder||a.WebKitBlobBuilder||a.MozBlobBuilder||a.MSBlobBuilder||(function(p){var f=function(A){return Object.prototype.toString.call(A).match(/^\[object\s(.*)\]$/)[1]},z=function l(){this.data=[]},y=function h(C,A,B){this.data=C;this.size=C.length;this.type=A;this.encoding=B},q=z.prototype,x=y.prototype,t=p.FileReaderSync,d=function(A){this.code=this[this.name=A]},r=("NOT_FOUND_ERR SECURITY_ERR ABORT_ERR NOT_READABLE_ERR ENCODING_ERR NO_MODIFICATION_ALLOWED_ERR INVALID_STATE_ERR SYNTAX_ERR").split(" "),w=r.length,k=p.URL||p.webkitURL||p,u=k.createObjectURL,e=k.revokeObjectURL,j=k,o=p.btoa,i=p.atob,s=false,n=function(A){s=!A},g=p.ArrayBuffer,m=p.Uint8Array;y.fake=x.fake=true;while(w--){d.prototype[r[w]]=w+1}try{if(m){n.apply(0,new m(1))}}catch(v){}if(!k.createObjectURL){j=p.URL={}}j.createObjectURL=function(B){var C=B.type,A;if(C===null){C="application/octet-stream"}if(B instanceof y){A="data:"+C;if(B.encoding==="base64"){return A+";base64,"+B.data}else{if(B.encoding==="URI"){return A+","+decodeURIComponent(B.data)}}if(o){return A+";base64,"+o(B.data)}else{return A+","+encodeURIComponent(B.data)}}else{if(u){return u.call(k,B)}}};j.revokeObjectURL=function(A){if(A.substring(0,5)!=="data:"&&e){e.call(k,A)}};q.append=function(E){var G=this.data;if(m&&(E instanceof g||E instanceof m)){if(s){G.push(String.fromCharCode.apply(String,new m(E)))}else{var F="",B=new m(E),C=0,D=B.length;for(;C<D;C++){F+=String.fromCharCode(B[C])}}}else{if(f(E)==="Blob"||f(E)==="File"){if(t){var A=new t;G.push(A.readAsBinaryString(E))}else{throw new d("NOT_READABLE_ERR")}}else{if(E instanceof y){if(E.encoding==="base64"&&i){G.push(i(E.data))}else{if(E.encoding==="URI"){G.push(decodeURIComponent(E.data))}else{if(E.encoding==="raw"){G.push(E.data)}}}}else{if(typeof E!=="string"){E+=""}G.push(unescape(encodeURIComponent(E)))}}}};q.getBlob=function(A){if(!arguments.length){A=null}return new y(this.data.join(""),A,"raw")};q.toString=function(){return"[object BlobBuilder]"};x.slice=function(D,A,C){var B=arguments.length;if(B<3){C=null}return new y(this.data.slice(D,B>1?A:this.data.length),C,this.encoding)};x.toString=function(){return"[object Blob]"};return z}(a));return function c(g,f){var j=f?(f.type||""):"";var e=new b();if(g){for(var h=0,d=g.length;h<d;h++){e.append(g[h])}}return e.getBlob(j)}}(self))};